name: Build from ZIP (final)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find & unzip project ZIP
        shell: bash
        run: |
          set -e
          ZIP=$(ls -1 *.zip | head -n1)
          if [ -z "$ZIP" ]; then echo "ZIP not found in repo root"; exit 1; fi
          echo "Found ZIP: $ZIP"
          rm -rf src_proj || true
          mkdir -p src_proj
          unzip -q "$ZIP" -d src_proj
          PROJ=$(ls -d src_proj/*/ | head -n1 | sed 's:/$::')
          echo "PROJ=$PROJ" | tee -a $GITHUB_ENV

      - name: JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Android SDK
        uses: android-actions/setup-android@v3

      - name: Install platforms & build-tools
        run: |
          yes | sdkmanager --licenses
          sdkmanager --install "platforms;android-34" "build-tools;34.0.0"

      - name: Bootstrap Gradle wrapper (8.7)
        shell: bash
        run: |
          set -e
          cd "$PROJ"
          if [ ! -f "./gradlew" ]; then
            curl -s "https://get.sdkman.io" | bash
            source "$HOME/.sdkman/bin/sdkman-init.sh"
            sdk install gradle 8.7
            gradle wrapper --gradle-version 8.7
          fi
          chmod +x ./gradlew
          ./gradlew --version

      - name: Assemble Debug & Release
        run: |
          set -e
          cd "$PROJ"
          ./gradlew --no-daemon assembleDebug assembleRelease

      - name: Collect APKs
        run: |
          mkdir -p _apks
          find "$PROJ" -name "*.apk" -print -exec cp -v {} _apks/ \;

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: _apks/
