name: Build from ZIP (auto)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ШАГ 01 — Скачать код
        uses: actions/checkout@v4

      - name: ШАГ 02 — Инструменты распаковки
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: ШАГ 03 — Найти ZIP и распаковать
        run: |
          set -e
          ZIP=$(ls -1 *.zip | head -n1)
          if [ -z "$ZIP" ]; then echo "ZIP не найден в корне"; exit 1; fi
          echo "Найден ZIP: $ZIP"
          unzip -o "$ZIP" -d .

      - name: ШАГ 04 — JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: ШАГ 05 — Android SDK
        uses: android-actions/setup-android@v2
        with:
          packages: |
            platforms;android-34
            build-tools;34.0.0

      - name: ШАГ 06 — Включить AndroidX и JVM args
        run: |
          PROJ=$(ls -d */ | head -n1 | sed 's:/$::')
          echo "Проект: $PROJ"
          cd "$PROJ"
          echo "android.useAndroidX=true" >> gradle.properties || true
          echo "android.enableJetifier=true" >> gradle.properties || true
          echo "org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8" >> gradle.properties || true

      - name: ШАГ 07 — Сборка DEBUG (подробные логи)
        run: |
          PROJ=$(ls -d */ | head -n1 | sed 's:/$::')
          cd "$PROJ"
          ./gradlew --version || (chmod +x gradlew && ./gradlew --version)
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: ШАГ 08 — Сборка RELEASE (подробные логи)
        continue-on-error: true
        run: |
          PROJ=$(ls -d */ | head -n1 | sed 's:/$::')
          cd "$PROJ"
          ./gradlew assembleRelease --stacktrace --no-daemon

      - name: ШАГ 09 — Найти APK и переименовать
        run: |
          set -e
          PROJ=$(ls -d */ | head -n1 | sed 's:/$::')
          cd "$PROJ"
          APKDBG=$(find . -path "*/outputs/apk/*/*" -name "*-debug*.apk" -o -name "app-debug.apk" | head -n1 || true)
          APKREL=$(find . -path "*/outputs/apk/*/*" -name "*-release*.apk" -o -name "app-release*.apk" | head -n1 || true)
          mkdir -p ../_apks
          [ -n "$APKDBG" ] && cp "$APKDBG" ../_apks/app-debug.apk
          [ -n "$APKREL" ] && cp "$APKREL" ../_apks/app-release-unsigned.apk
          cd ..
          ls -l _apks || (echo "APK не найден"; exit 1)

      - name: ШАГ 10 — Сохранить APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: _apks/
